"""dislike separate entity

Revision ID: c3bdaab46325
Revises: 09b0da368871
Create Date: 2024-07-25 12:11:18.757260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bdaab46325'
down_revision = '09b0da368871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('dislike_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('disliked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dislike_id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('is_like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_like', sa.BOOLEAN(), nullable=True))

    op.drop_table('dislikes')
    # ### end Alembic commands ###
